# Generated by Django 4.0.3 on 2022-04-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'alltask'},
        ),
        migrations.AddField(
            model_name='task',
            name='author2',
            field=models.TextField(default='anonim'),
        ),
    ]
