# Generated by Django 4.0.3 on 2022-04-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_task_options_task_author2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author2',
        ),
    ]
